theme = "arkansas"
baseURL = "https://roymckenzie4.github.io/"
languageCode = 'en-us'
title = "home"

# Menu
[menu]
  # Header menu
  [[menu.main]]
    url = "/park/"
    name = "state parked"
    weight = 1
